[project]
name = "VelumX"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []
[contracts.paymaster]
path = "contracts/paymaster.clar"
clarity_version = 3
epoch = 3.0


[contracts.sip-010-trait-ft-standard]
path = "contracts/traits/sip-010-trait-ft-standard.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
